name: Delete branch stack

on:
  delete:

permissions:
  id-token: write
  contents: read

jobs:
  delete-merged-branch:
    name: Delete merged branch
    runs-on: ubuntu-latest
    environment: development
    timeout-minutes: 15
    steps:
      - name: Pull Repository
        uses: actions/checkout@v3

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get Stack Name
        id: get-stack-name
        uses: alphagov/di-github-actions/beautify-branch-name@c6ee88734260ae374365bbe2b76ebe2553b3df19
        with:
          branch-name: ${{ github.event.ref }}
          set-env-var: stack-name
          length-limit: ${{ vars.STACK_NAME_LENGTH }}
          usage: Stack name
          prefix: db-rpt

      - name: Delete stacks
        uses: alphagov/di-github-actions/sam/delete-stacks@ad7ff02640e256ecc3f677bc876ac0a22ed25964
        with:
          stack-names: ${{ env.stack-name }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Report delete
        env:
          STACK_NAME: $${{ env.stack-name }}
        run: echo "Deleted stack \`$STACK_NAME\`" >> "$GITHUB_STEP_SUMMARY"
