export enum EventTypes {
  AccountBlock = "accountBlock",
  AccountConcern = "accountConcern",
  AccountPurged = "accountPurged",
  AccountCredentialChangeRequired = "accountCredentialChangeRequired",
  AccountDisabled = "accountDisabled",
  AccountEnabled = "accountEnabled",
  CredentialCompromise = "credentialCompromise",
  DeviceConcern = "deviceConcern",
  OptIn = "optIn",
  OptOutInitiated = "optOutInitiated",
  OptOutCancelled = "optOutCancelled",
  OptOutEffective = "optOutEffective",
  RecoveryActivated = "recoveryActivated",
  RecoveryInformationChanged = "recoveryInformationChanged",
  SessionsRevoked = "sessionsRevoked",
}

export const validEventKeys: Array<EventTypes> = [
  EventTypes.AccountBlock,
  EventTypes.AccountConcern,
  EventTypes.AccountPurged,
  EventTypes.AccountCredentialChangeRequired,
  EventTypes.AccountDisabled,
  EventTypes.AccountEnabled,
  EventTypes.CredentialCompromise,
  EventTypes.DeviceConcern,
  EventTypes.OptIn,
  EventTypes.OptOutInitiated,
  EventTypes.OptOutCancelled,
  EventTypes.OptOutEffective,
  EventTypes.RecoveryActivated,
  EventTypes.RecoveryInformationChanged,
  EventTypes.SessionsRevoked,
];

export enum issSubEventURIs {
  accountBlock = "https://vocab.account.gov.uk/secevent/v1/notification/accountBlock",
  accountConcern = "https://vocab.account.gov.uk/secevent/v1/notification/accountConcern",
  accountPurged = "https://schemas.openid.net/secevent/risc/event-type/account-purged",
  accountCredentialChangeRequired = "https://schemas.openid.net/secevent/risc/event-type/account-credential-change-required",
  accountDisabled = "https://schemas.openid.net/secevent/risc/event-type/account-disabled",
  accountEnabled = "https://schemas.openid.net/secevent/risc/event-type/account-enabled",
  credentialCompromise = "https://schemas.openid.net/secevent/risc/event-type/credential-compromise",
  deviceConcern = "https://vocab.account.gov.uk/secevent/v1/notification/deviceConcern",
  optIn = "https://schemas.openid.net/secevent/risc/event-type/opt-in",
  optOutInitiated = "https://schemas.openid.net/secevent/risc/event-type/opt-out-initiated",
  optOutCancelled = "https://schemas.openid.net/secevent/risc/event-type/opt-out-cancelled",
  optOutEffective = "https://schemas.openid.net/secevent/risc/event-type/opt-out-effective",
  recoveryActivated = "https://schemas.openid.net/secevent/risc/event-type/recovery-activated",
  recoveryInformationChanged = "https://schemas.openid.net/secevent/risc/event-type/recovery-information-changed",
  sessionsRevoked = "https://schemas.openid.net/secevent/risc/event-type/sessions-revoked",
}
